### ISSUE TITLE
Sofiana.ai

### ISSUE THREAD

**Issue by pgschr** [Bloomberg-Beta/Manual#126]
Hello, we are a fintech startup that is doing the opposite of everybody else: instead of disrupting the traditional banking industry, we help community banks and credit unions compete with new digital-based entrants. 

We do this by increasing the efficiency in bank management, and we use Artificial Intelligence to achieve this. To that end, we are currently building an AI-based stress testing application that helps banks lower capital requirements and increase their investment levels, all in a more controlled risk environment. We strongly believe that stress testing is a strategic tool that greatly helps bankers manage their banks. And AI brings to the table a new paradigm in bank risk management.

Last, the venture is a great fit with Bloomberg, as Sofiana's applications are data-driven, largely use industry datasets, and target banks can be cross-sold with current Bloomberg bank clients.

More info at our website, Sofiana.ai, and in our [investors deck](http://sofiana.ai/Sofiana%20investor%20deck.pdf)

Best,
Pablo Schor
https://www.linkedin.com/in/pschor/

**Comment by roybahat** [comment]
Thank you... unfortunately (as we may out here) we actively avoid investing in financial services.

**Comment by pgschr** [comment]
Even when it's a good fit with Bloomberg that may be even interested in acquiring the company when it grows as it shares the same customer base?

**Comment by roybahat** [comment]
Yes, we are specifically indifferent to that and explain why here on this site. We are focused on financial returns, and not on strategic fit with Bloomberg.
