### ISSUE TITLE
Investor checklist 404

### ISSUE THREAD

**Issue by mralexho** [Bloomberg-Beta/Manual#23]
Hello, while reading the [operating manual](https://github.com/Bloomberg-Beta/Manual/blob/master/1%20-%20Manual.md#what-we-look-for), I noticed the investor checklist link is broken.

https://github.com/Bloomberg-Beta/Manual/blob/morganpolotan-investor-checklist/3%20-%20Investor%20checklist.md

**Comment by morganpolotan** [comment]
Fixed the links, thanks for raising mralexho!

**Comment by mralexho** [comment]
Thanks for being transparent!
