### ISSUE TITLE
$150M fund? two $75M funds?

### ISSUE THREAD

**Issue by andreseg** [Bloomberg-Beta/Manual#68]
Unclear if this is saying $75M is for initial checks and $75M is for follow ons, or if it's outdated.

![image](https://user-images.githubusercontent.com/13453719/49653497-20fb8300-fa03-11e8-8926-5f453571ba58.png)

**Comment by hjs** [comment]
Fixed here: https://github.com/Bloomberg-Beta/Manual/commit/e6ff1539a592abd3bf1bd27ec02fff0d534db9d7
