### ISSUE TITLE
Do you invest in Chilean startups?

### ISSUE THREAD

**Issue by matiaslopezd** [Bloomberg-Beta/Manual#72]
Here in Chile (the last country in the south pole of America) is very dificult find a real early stage VC. They never understand about the real use of technology, because prefer the classic business with less risks. Maybe that is because the economic policies of my country are not focus for greater technological growth.

It is very disappointing not to have a real possibilities of financial support and innovative investors. I'm sure that my startup can growth more fast with better business environment, than currently we make it now.

My startup is focused on customer service with a integration of video conference platforms like SaaS. Also with extensions in Markeplace like facial recognition, sentiment analitycs, and more!

Maybe can I have chances to talk with anyone? I hope that can be my chance to change the industries of customer service!

Thanks, I love Bloomberg!

**Comment by angelamartin** [comment]
Hello, thank you for reaching out. Unfortunately, we're one of the VCs who continues to avoid investing outside of places we already know. You can see our criteria here: https://github.com/Bloomberg-Beta/Manual/blob/master/3%20-%20Criteria%20for%20investing.md. 
Good luck!

**Comment by matiaslopezd** [comment]
Hi @angelamartin! And now? :smile:

**Comment by angelamartin** [comment]
Hello, given how remote the world is today, we have started meeting founders across the United States more broadly. However, we still refrain from investing outside of the U.S., given our perspective that as early stage investors, our ability to evaluate companies without local expertise is limited.
