### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by yasyf** [Bloomberg-Beta/Manual#82]
Hey! Just a heads up that the link on the bullet that reads "Background check conducted, any issues discussed" on L65 of [3 - Criteria for investing.md](https://github.com/Bloomberg-Beta/Manual/blob/master/3%20-%20Criteria%20for%20investing.md#founders-and-team-2) has a broken link to `highly.co`.

**Comment by roybahat** [comment]
Fixed -- tx!
