### ISSUE TITLE
Broken links to old Also by Roy Bahat posts in manual

### ISSUE THREAD

**Issue by rmill360** [Bloomberg-Beta/Manual#89]
I noticed a few links in the manual page are pointing to 404s on also.roybahat.com

Line 97: 
-We believe progress requires an accumulation of many small and large decisions over years – [trust takes time](http://also.roybahat.com/post/91847335194/the-trust-thing). That said, we commit to act now. Specifically:
+We believe progress requires an accumulation of many small and large decisions over years – [trust takes time](https://also.roybahat.com/the-trust-thing-691791a4c6ca). That said, we commit to act now. Specifically:

Line 176:
-A demo is 50 times more useful than slides. One is a description of a thing, the other is the thing itself. We look at your demo [the way a new user would](http://also.roybahat.com/post/82904179747/why-most-demos-confuse).
+A demo is 50 times more useful than slides. One is a description of a thing, the other is the thing itself. We look at your demo [the way a new user would](https://also.roybahat.com/why-most-demos-confuse-79051934a77).
 
Line 228:
-* [How’s it going?](http://also.roybahat.com/post/62158854505/a-dumb-question-to-ask-an-entrepreneur)
+* [How’s it going?](https://also.roybahat.com/a-dumb-question-to-ask-an-entrepreneur-db737b3c7d6a)
  
Line 313:
-We are [not big fans of boards](http://also.roybahat.com/post/102969262108/boreds) in day-zero companies. While we like founders having a close circle of trusted colleagues to ask for advice and we aspire to be in that trusted circle, when we imagine early-stage founders working on slide decks instead of products, it makes us feel a little ill. We'd rather be in your Slack or getting your Github notifications than having you prepare for meetings.
+We are [not big fans of boards](https://also.roybahat.com/boreds-7c4c33bda84a) in day-zero companies. While we like founders having a close circle of trusted colleagues to ask for advice and we aspire to be in that trusted circle, when we imagine early-stage founders working on slide decks instead of products, it makes us feel a little ill. We'd rather be in your Slack or getting your Github notifications than having you prepare for meetings.
 
Line 333:
-Our standard first check is $500,000, though more and more often we are investing up to $1M. We want to invest enough to give a startup the money it needs to make real progress in the early days, and to attract other investors alongside us if needed. We are happy to lead, and happy to participate in rounds led by others, depending on the situation -- in earliest-stage venture, sometimes the [idea of a lead means different things to different people](http://also.roybahat.com/post/119369807637/in-earliest-stage-venture-what-is-a-lead-anyway).
+Our standard first check is $500,000, though more and more often we are investing up to $1M. We want to invest enough to give a startup the money it needs to make real progress in the early days, and to attract other investors alongside us if needed. We are happy to lead, and happy to participate in rounds led by others, depending on the situation -- in earliest-stage venture, sometimes the [idea of a lead means different things to different people](https://also.roybahat.com/in-earliest-stage-venture-what-is-a-lead-anyway-e60c4e08bb7e).

**Comment by hjs** [comment]
Thanks for catching these! Fixed.
