### ISSUE TITLE
Pitch Meeting

### ISSUE THREAD

**Issue by GMBInnovationHub** [Bloomberg-Beta/Manual#97]
What is the process to get a pitch meeting? Are you interesting in investing in a fitness technology company? What are the funds sweet spots? I am looking for $250k in early stage

**Comment by mkim383** [comment]
Hi there! Thanks for reaching out. Unfortunately, fitness is farther afield from our focus on the future of work. Regarding sweet spots and typical check size, we're transparent about our investing here -- https://github.com/Bloomberg-Beta/Manual/blob/master/1%20-%20Manual.md#what-we-believe-about-the-future-of-work
